logging:
    level: 
        org.springframework.security.web: DEBUG

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/loxodonta?createDatabaseIfNotExist=true
        username: lion
        password: L10n*L0x0dont4
        driver-class-name: com.mysql.cj.jdbc.Driver
    security:
        user:
            name: test-user
            password: 123456789
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                ddl-auto: update

app:
    security:
        issuer: ng-software
        secret: J1wsiRoSUs1*

